### ISSUE TITLE
another independent collection

### ISSUE THREAD

**Issue by prik-k** [syxanash/awesome-web-desktops#30]
hey @syxanash, just discovered your awesome collection of web-desktops. 

I guess we both have a knack for OS stuff as I too happen to have made a more recent list of them and would to hear your feedback on it. 

I made this list being completely unaware that yours exist still we do not overlap much and I was wondering to extend it even further. Any suggestions?

[here it is](https://github.com/prik-k/awesome-OS)

**Comment by syxanash** [comment]
Hi @prik-k great collection!
Keep up the good work ;)
