### ISSUE TITLE
Would CollabVM count as a web desktop?

### ISSUE THREAD

**Issue by dartzcn** [syxanash/awesome-web-desktops#37]
Hi! 

I run a site called CollabVM, and I was wondering if it would count as a "web desktop", as the website runs several collaborative desktop virtual machines that anyone can control.

Here's the link: https://computernewb.com/collab-vm/ 

Do let me know, cause I'd love to add it here.

**Comment by syxanash** [comment]
Hi there!
I came across your fantastic project a while ago, it's really impressive! Unfortunately though, I prefer adding projects which don't involve Virtual Machines but more web technologies for building web desktops.
I really admire your project and good luck with the development!
