### ISSUE TITLE
Can this be a community?

### ISSUE THREAD

**Issue by DustinBrett** [syxanash/awesome-web-desktops#47]
I love this repo and your website @syxanash. I feel like this list may be the best source that exists for web desktops. I'm just wondering if you've considered starting some kind of community like a Discord channel? I've looked around for some kind of community about "websites, web apps and portfolios which resemble desktop operating systems" but haven't found anything centralized or maintained. If you were to start such a channel and add it to the README, I'd love to be a part of it! #WebDesktopCon2027

**Comment by syxanash** [comment]
Hi Dustin, I've actually seen so much interest in recent years around Web Desktops, maybe not for enterprise web apps but certainly lots of portfolios and side projects!
At the moment I wouldn't have enough time to maintain such a community, but if someone else comes up with a discord or any other medium I'd definitely contribute as well 😊
