### ISSUE TITLE
web3os

### ISSUE THREAD

**Issue by milahu** [syxanash/awesome-web-desktops#54]
just found this

- source https://github.com/web3os-org/kernel
- live demo https://web3os.sh/
- reddit https://www.reddit.com/r/javascript/comments/yc5yfu/web3os_id_like_to_introduce_yall_to_something_ive/

**Comment by syxanash** [comment]
Hi this is a fantastic project, really great find!
Although I'd rather wait before putting it on the directory, as the project looks very early stage 🤔 
I was able to boot the desktop only on chrome and after waiting a very long time. I'll keep the PR open and monitor the project!

Thanks again for your submission!
